# A Sample Nginx deployment that can be use as an x86 Example.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x86-workloads
spec:
  replicas: 50
  selector:
    matchLabels:
      app: x86-app
  template:
    metadata:
      labels:
        app: x86-app
    spec:
      containers:
      - name: x86-app
        image: nginx
        resources:
          requests:
            cpu: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "opsfleet-team"
                  operator: "In"
                  values: ["team-X"]